# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo app
pod 'Alamofire'

  target 'Demo appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Demo appUITests' do
    # Pods for testing
  end

end
